# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Install ts-node-dev globally just in case
RUN npm install -g ts-node-dev

COPY . .

EXPOSE 3000

# Use your dev script
CMD ["npm", "run", "dev"]
