# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

COPY . .

EXPOSE 3000

COPY tsconfig.json .
COPY development/nodemon.json ./development/nodemon.json
COPY development/tsconfig.dev.json ./development/tsconfig.dev.json